name: CI
on:
  push:
    branches: [main]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
  pull_request:
    branches: [main]
    paths-ignore:
      - 'README.md'
      - 'docs/**'

permissions:
  pull-requests: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
  test:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [built, committed]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
 
      - name: Create Pull Request
        id: cpr
        uses: ./
        with:
          commit-message: '[CI] test ${{ matrix.target }}'
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          title: '[CI] test ${{ matrix.target }}'
          body: |
            - CI test case for target '${{ matrix.target }}'
            Auto-generated by [create-pull-request][1]
            [1]: https://github.com/marceloalbam/create-pull-request
          branch: ci-test-${{ matrix.target }}

  package:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Pull Request
        uses: marceloalbam/create-pull-request@v2
        with:
          commit-message: 'build: update distribution'
          title: Update distribution
          body: |
            - Updates the distribution for changes on `main`
            Auto-generated by [create-pull-request][1]
            [1]: https://github.com/marceloalbam/create-pull-request
          branch: update-distribution
